version: '2'
services:
 flask_front:
  image: nginx
  volumes:
   - ./templates:/etc/nginx/templates
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
 flask_engine:
   build: .
   restart: always
   expose:
     - 5000
   volumes:
     - ./app:/app:ro
